# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a47e771671e1f6ca5b83beab14ddaded7fd73ad2e483dfeeae319259f89dec18dbf121d24bc4ab7c5247bb9827553f11a0fcab9c23fca6ee3345baef2aa3e3dc

test:
  secret_key_base: 708df52fbfd244c3ef21faf52cd795b7846713b723bc1e4724a1220097e80a2b7bcca251d70600f80c54cbb051f53186078e9572680e524d6356a9d469f12b6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
